# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='config.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x63onfig.proto\"\x94\x05\n\x06\x43onfig\x12\x1c\n\x05model\x18\x01 \x01(\x0b\x32\r.Config.Model\x12\x1a\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x0c.Config.Data\x12\"\n\x08training\x18\x03 \x01(\x0b\x32\x10.Config.Training\x12\x11\n\x04seed\x18\x04 \x01(\x05:\x03\x33\x31\x31\x12\x1a\n\x04test\x18\x05 \x01(\x0b\x32\x0c.Config.Test\x1a\x15\n\x05Model\x12\x0c\n\x04\x61rch\x18\x01 \x01(\t\x1a\x61\n\x04\x44\x61ta\x12\x0f\n\x07\x64\x61taset\x18\x01 \x02(\t\x12\x0c\n\x04path\x18\x02 \x02(\t\x12\x13\n\x0btrain_split\x18\x03 \x01(\t\x12\x11\n\tval_split\x18\x04 \x01(\t\x12\x12\n\ntest_split\x18\x05 \x01(\t\x1a\x96\x02\n\x08Training\x12\x13\n\x0bnum_workers\x18\x01 \x01(\x05\x12\r\n\x05\x65poch\x18\x02 \x01(\x05\x12\x12\n\nbatch_size\x18\x03 \x01(\x05\x12\x11\n\tval_epoch\x18\x04 \x01(\x05\x12\x11\n\tdisp_iter\x18\x05 \x01(\x05\x12-\n\toptimizer\x18\x06 \x01(\x0b\x32\x1a.Config.Training.Optimizer\x12#\n\x04loss\x18\x07 \x01(\x0b\x32\x15.Config.Training.Loss\x12\x13\n\x0bresume_path\x18\x08 \x01(\t\x1a%\n\tOptimizer\x12\n\n\x02lr\x18\x02 \x01(\x01\x12\x0c\n\x04\x61rgs\x18\x03 \x01(\t\x1a\x1c\n\x04Loss\x12\x14\n\x0csize_average\x18\x01 \x01(\x08\x1aj\n\x04Test\x12\x12\n\nmodel_path\x18\x01 \x01(\t\x12\x12\n\nimage_path\x18\x02 \x01(\t\x12\x13\n\x0boutput_path\x18\x03 \x01(\t\x12%\n\x16\x65valuate_on_test_split\x18\x04 \x01(\x08:\x05\x66\x61lse')
)




_CONFIG_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='Config.Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='arch', full_name='Config.Model.arch', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=189,
)

_CONFIG_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='Config.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dataset', full_name='Config.Data.dataset', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='Config.Data.path', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='train_split', full_name='Config.Data.train_split', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val_split', full_name='Config.Data.val_split', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test_split', full_name='Config.Data.test_split', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=288,
)

_CONFIG_TRAINING_OPTIMIZER = _descriptor.Descriptor(
  name='Optimizer',
  full_name='Config.Training.Optimizer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lr', full_name='Config.Training.Optimizer.lr', index=0,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='args', full_name='Config.Training.Optimizer.args', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=502,
  serialized_end=539,
)

_CONFIG_TRAINING_LOSS = _descriptor.Descriptor(
  name='Loss',
  full_name='Config.Training.Loss',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size_average', full_name='Config.Training.Loss.size_average', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=541,
  serialized_end=569,
)

_CONFIG_TRAINING = _descriptor.Descriptor(
  name='Training',
  full_name='Config.Training',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_workers', full_name='Config.Training.num_workers', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='epoch', full_name='Config.Training.epoch', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='Config.Training.batch_size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val_epoch', full_name='Config.Training.val_epoch', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disp_iter', full_name='Config.Training.disp_iter', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='optimizer', full_name='Config.Training.optimizer', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='loss', full_name='Config.Training.loss', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resume_path', full_name='Config.Training.resume_path', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CONFIG_TRAINING_OPTIMIZER, _CONFIG_TRAINING_LOSS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=569,
)

_CONFIG_TEST = _descriptor.Descriptor(
  name='Test',
  full_name='Config.Test',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_path', full_name='Config.Test.model_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_path', full_name='Config.Test.image_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_path', full_name='Config.Test.output_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='evaluate_on_test_split', full_name='Config.Test.evaluate_on_test_split', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=571,
  serialized_end=677,
)

_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='Config.model', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='Config.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='training', full_name='Config.training', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seed', full_name='Config.seed', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=311,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test', full_name='Config.test', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CONFIG_MODEL, _CONFIG_DATA, _CONFIG_TRAINING, _CONFIG_TEST, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=677,
)

_CONFIG_MODEL.containing_type = _CONFIG
_CONFIG_DATA.containing_type = _CONFIG
_CONFIG_TRAINING_OPTIMIZER.containing_type = _CONFIG_TRAINING
_CONFIG_TRAINING_LOSS.containing_type = _CONFIG_TRAINING
_CONFIG_TRAINING.fields_by_name['optimizer'].message_type = _CONFIG_TRAINING_OPTIMIZER
_CONFIG_TRAINING.fields_by_name['loss'].message_type = _CONFIG_TRAINING_LOSS
_CONFIG_TRAINING.containing_type = _CONFIG
_CONFIG_TEST.containing_type = _CONFIG
_CONFIG.fields_by_name['model'].message_type = _CONFIG_MODEL
_CONFIG.fields_by_name['data'].message_type = _CONFIG_DATA
_CONFIG.fields_by_name['training'].message_type = _CONFIG_TRAINING
_CONFIG.fields_by_name['test'].message_type = _CONFIG_TEST
DESCRIPTOR.message_types_by_name['Config'] = _CONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), dict(

  Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), dict(
    DESCRIPTOR = _CONFIG_MODEL,
    __module__ = 'config_pb2'
    # @@protoc_insertion_point(class_scope:Config.Model)
    ))
  ,

  Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(
    DESCRIPTOR = _CONFIG_DATA,
    __module__ = 'config_pb2'
    # @@protoc_insertion_point(class_scope:Config.Data)
    ))
  ,

  Training = _reflection.GeneratedProtocolMessageType('Training', (_message.Message,), dict(

    Optimizer = _reflection.GeneratedProtocolMessageType('Optimizer', (_message.Message,), dict(
      DESCRIPTOR = _CONFIG_TRAINING_OPTIMIZER,
      __module__ = 'config_pb2'
      # @@protoc_insertion_point(class_scope:Config.Training.Optimizer)
      ))
    ,

    Loss = _reflection.GeneratedProtocolMessageType('Loss', (_message.Message,), dict(
      DESCRIPTOR = _CONFIG_TRAINING_LOSS,
      __module__ = 'config_pb2'
      # @@protoc_insertion_point(class_scope:Config.Training.Loss)
      ))
    ,
    DESCRIPTOR = _CONFIG_TRAINING,
    __module__ = 'config_pb2'
    # @@protoc_insertion_point(class_scope:Config.Training)
    ))
  ,

  Test = _reflection.GeneratedProtocolMessageType('Test', (_message.Message,), dict(
    DESCRIPTOR = _CONFIG_TEST,
    __module__ = 'config_pb2'
    # @@protoc_insertion_point(class_scope:Config.Test)
    ))
  ,
  DESCRIPTOR = _CONFIG,
  __module__ = 'config_pb2'
  # @@protoc_insertion_point(class_scope:Config)
  ))
_sym_db.RegisterMessage(Config)
_sym_db.RegisterMessage(Config.Model)
_sym_db.RegisterMessage(Config.Data)
_sym_db.RegisterMessage(Config.Training)
_sym_db.RegisterMessage(Config.Training.Optimizer)
_sym_db.RegisterMessage(Config.Training.Loss)
_sym_db.RegisterMessage(Config.Test)


# @@protoc_insertion_point(module_scope)
